# Generated by Django 2.2.5 on 2019-10-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191009_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pval',
            name='PVALUE',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=52, max_length=100, null=True),
        ),
    ]
